config/routes.rb
WebApp::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "user/sessions", :registrations => "user/registrations" } 

  resources :users, shallow: true do
    collection do
      get 'email_check'
    end
    member do
      get 'password'
      put 'password'
    end 
    resource :user_setting
  end                     
  resources :properties
  resources :feedbacks 
  resources :authentications      

  root :to => 'welcome#index'

  match '/admin' => 'admin/dashboard#index'
  namespace :admin do
    resources :properties
    resources :users
    constraints CanAccessResque do
      mount Resque::Server, at: 'resque'
    end
  end

  match '/auth/:provider/callback' => 'authentications#create'   
  match 'dev' => 'dev#index', :via => [:get]
end

app/models/user_setting.rb
# coding: utf-8

class UserSetting < ActiveRecord::Base   
  # EDIT HERE
  SNS_TYPES = { 'facebook' => '페이스북', 'twitter' => '트위터', 'google' => 'google'}
  POST_SNS_TYPES = { 'like' => '좋아요', '...' => '...' }
  EMAIL_ME_TYPES = { 'comment' => '댓글알림' }
  PHONE_PUSH_TYPES = { 'follow' => '팔로우 알림' }
  

  belongs_to :user   
  validates_presence_of :term_agreed_at  
                                    
  
  def readable_object(version, current_user, includes = [])
    ret = {}   

    case version.to_i 
    when 1     
       ret = {
         id: id, 
         user_id: user_id,
         post_sns_with:    post_sns_with,
         post_sns_when:    post_sns_when,
         email_me_when:    email_me_when,
         phone_push_when:  phone_push_when,
         email_agree: email_agree,
         term_agree:  term_agree,
         created_at: created_at.to_s(:normal_datetime),
         updated_at: updated_at.to_s(:normal_datetime)
       }
    end

    ret
  end                               
  
         
  def term_agree
    term_agreed_at ? true : false
  end
  def email_agree
    email_agreed_at ? true : false
  end
  def term_agree=(agree)  
    if agree == true or agree == 'true'
      self.term_agreed_at = Time.zone.now
    else
      self.term_agreed_at = nil
    end
  end
  def email_agree=(agree)
    if agree == true or agree == 'true'
      self.email_agreed_at = Time.zone.now
    else
      self.email_agreed_at = nil
    end
  end  
  
  def post_sns_with
    SNS_TYPES.keys - Util.to_array(do_not_post_sns_with)
  end
  def post_sns_when
    POST_SNS_TYPES.keys - Util.to_array(do_not_post_sns_when)
  end
  def email_me_when
     EMAIL_ME_TYPES.keys - Util.to_array(do_not_email_me_when)
  end
  def phone_push_when
    PHONE_PUSH_TYPES.keys - Util.to_array(do_not_phone_push_when)
  end 
  
  def post_sns_with=(array)       
    do_not = SNS_TYPES.keys - array
    self.do_not_post_sns_with = Util.to_string(do_not)
  end
  def post_sns_when=(array)       
    do_not = POST_SNS_TYPES.keys - array
    self.do_not_post_sns_when = Util.to_string(do_not)
  end
  def email_me_when=(array)       
    do_not = EMAIL_ME_TYPES.keys - array
    self.do_not_email_me_when = Util.to_string(do_not)
  end
  def phone_push_when=(array)       
    do_not = PHONE_PUSH_TYPES.keys - array
    self.do_not_phone_push_when = Util.to_string(do_not)
  end
    
end

app/controllers/user_settings_controller.rb
class UserSettingsController < ApplicationController 
  before_filter :find_user
  
  def find_user
    @user = User.find(params[:user_id]) if params[:user_id].present?
  end
  
  def index
    @user_settings = UserSetting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render_collection_json @user_settings }
    end
  end

  def show          
    @user_setting = @user.user_setting

    respond_to do |format|
      format.html # show.html.erb
      format.json { render_resource_json @user_setting }
    end
  end

  def edit
    @user_setting = @user.user_setting
  end


  def update
    @user_setting = @user.user_setting

    respond_to do |format|
      if @user_setting.update_attributes(params[:user_setting])
        format.html { redirect_to edit_user_user_setting_path(@user), notice: 'Successfully updated.' }
        format.json { redirect_to user_user_setting_path(user_id: @user.id, format: 'json', v: params[:v]) }
      else
        format.html { render action: "edit" }
        format.json { render_fail_json @user_setting.errors.messages }
      end
    end
  end

end

app/helpers/user_settings_helper.rb
module UserSettingsHelper
end

app/views/user_settings/_form.html.erb
<% content_for :head do %>
<script type="text/javascript">
$(document).ready(function() {
	$('form').submit(function(){
		addBlankIfAllUnchecked('user_setting[post_sns_with][]', 'post-sns-with-check');
		addBlankIfAllUnchecked('user_setting[post_sns_when][]', 'post-sns-when-check');
		addBlankIfAllUnchecked('user_setting[email_me_when][]', 'email-me-when-check');
		addBlankIfAllUnchecked('user_setting[phone_push_when][]', 'phone-push-when-check');
		addBlankIfAllUnchecked('user_setting[email_agree]', 'email-agree-check');
	});
});   

function addBlankIfAllUnchecked(name, checkboxClassName){
	var checkedCnt = $('.' + checkboxClassName + ':checked').length;
	if (checkedCnt == 0) {       
		var input = $("<input>").attr("type", "hidden").attr("name", name).val("");
		$('form').append($(input));
	};
}                                            

</script>
<% end %>


<%= form_for(@user_setting, url: "/users/#{@user.id}/user_setting") do |f| %>
  <% if @user_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_setting.errors.count, "error") %> prohibited this user_setting from being saved:</h2>

      <ul>
      <% @user_setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= label_tag 'Post sns with:' %><br />       
		<% UserSetting::SNS_TYPES.each do |k, v| %>        
			<%= check_box_tag("user_setting[post_sns_with][]", k, @user_setting.post_sns_with.include?(k), :class => 'post-sns-with-check') %>           
			<%= label_tag v %><br />     
		<% end %>
  </div> 

  <div class="field">
    <%= label_tag 'Post sns when:' %><br />       
		<% UserSetting::POST_SNS_TYPES.each do |k, v| %>        
			<%= check_box_tag("user_setting[post_sns_when][]", k, @user_setting.post_sns_when.include?(k), :class => 'post-sns-when-check') %>           
			<%= label_tag v %><br />     
		<% end %>
  </div>

  <div class="field">
    <%= label_tag 'Email me when:' %><br />       
		<% UserSetting::EMAIL_ME_TYPES.each do |k, v| %>        
			<%= check_box_tag("user_setting[email_me_when][]", k, @user_setting.email_me_when.include?(k), :class => 'email-me-when-check') %>           
			<%= label_tag v %><br />     
		<% end %>
  </div>

  <div class="field">
    <%= label_tag 'Phone push when:' %><br />       
		<% UserSetting::PHONE_PUSH_TYPES.each do |k, v| %>        
			<%= check_box_tag("user_setting[phone_push_when][]", k, @user_setting.phone_push_when.include?(k), :class => 'phone-push-when-check') %>           
			<%= label_tag v %><br />     
		<% end %>
  </div>


  <div class="field">
    <%= label_tag :email_agree %><br />                                                                                    
		<%= check_box_tag("user_setting[email_agree]", true, !@user_setting.email_agreed_at.nil?, :class => 'email-agree-check') %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_settings/edit.html.erb
<h1>Editing user_setting</h1>

<%= render 'form' %>

app/views/user_settings/index.html.erb
<h1>Listing user_settings</h1>

<table>
  <tr>
    <th>User</th>
    <th>Post sns with</th>
    <th>Post sns when</th>
    <th>Email me when</th>
    <th>Phone push me when</th>
    <th>Email agreed at</th>
    <th>Term agreed at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_settings.each do |user_setting| %>
  <tr>
    <td><%= user_setting.user_id %></td>
    <td><%= user_setting.do_not_post_sns_with %></td>
    <td><%= user_setting.do_not_post_sns_when %></td>
    <td><%= user_setting.do_not_email_me_when %></td>
    <td><%= user_setting.do_not_phone_push_when %></td>
    <td><%= user_setting.email_agreed_at %></td>
    <td><%= user_setting.term_agreed_at %></td>
    <td><%= link_to 'Show', user_setting %></td>
    <td><%= link_to 'Edit', edit_user_setting_path(user_setting) %></td>
    <td><%= link_to 'Destroy', user_setting, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User setting', new_user_setting_path %>

app/views/user_settings/new.html.erb
<h1>New user_setting</h1>

<%= render 'form' %>

<%= link_to 'Back', user_settings_path %>

app/views/user_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_setting.user_id %>
</p>

<p>
  <b>Post sns with:</b>
  <%= @user_setting.do_not_post_sns_with %>
</p>

<p>
  <b>Post sns when:</b>
  <%= @user_setting.do_not_post_sns_when %>
</p>

<p>
  <b>Email me when:</b>
  <%= @user_setting.do_not_email_me_when %>
</p>

<p>
  <b>Phone push me when:</b>
  <%= @user_setting.do_not_phone_push_when %>
</p>

<p>
  <b>Email agreed at:</b>
  <%= @user_setting.email_agreed_at %>
</p>

<p>
  <b>Term agreed at:</b>
  <%= @user_setting.term_agreed_at %>
</p>


<%= link_to 'Edit', edit_user_setting_path(@user_setting) %> |
<%= link_to 'Back', user_settings_path %>