config/routes.rb
WebApp::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "user/sessions", :registrations => "user/registrations" } 

  resources :users, shallow: true do
    collection do
      get 'email_check'
    end
    member do
      get 'password'
      put 'password'
    end 
    resource :user_setting
  end                     
  resources :properties
  resources :feedbacks 
  resources :authentications      

  root :to => 'welcome#index'

  match '/admin' => 'admin/dashboard#index'
  namespace :admin do
    resources :properties
    resources :users
    constraints CanAccessResque do
      mount Resque::Server, at: 'resque'
    end
  end

  match '/auth/:provider/callback' => 'authentications#create'   
  match 'dev' => 'dev#index', :via => [:get]
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :user
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < InheritedResources::Base
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :feedback_type %><br />
    <%= f.text_field :feedback_type %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<table>
  <tr>
    <th>Feedback type</th>
    <th>User</th>
    <th>Email</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedbacks.each do |feedback| %>
  <tr>
    <td><%= feedback.feedback_type %></td>
    <td><%= feedback.user_id %></td>
    <td><%= feedback.email %></td>
    <td><%= feedback.content %></td>
    <td><%= link_to 'Show', feedback %></td>
    <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
    <td><%= link_to 'Destroy', feedback, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Feedback type:</b>
  <%= @feedback.feedback_type %>
</p>

<p>
  <b>User:</b>
  <%= @feedback.user_id %>
</p>

<p>
  <b>Email:</b>
  <%= @feedback.email %>
</p>

<p>
  <b>Content:</b>
  <%= @feedback.content %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>