config/routes.rb
WebApp::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "user/sessions", :registrations => "user/registrations" } 

  resources :users, shallow: true do
    collection do
      get 'email_check'
    end
    member do
      get 'password'
      put 'password'
    end 
    resource :user_setting
  end                     
  resources :properties
  resources :feedbacks 
  resources :authentications      

  root :to => 'welcome#index'

  match '/admin' => 'admin/dashboard#index'
  namespace :admin do
    resources :properties
    resources :users
    constraints CanAccessResque do
      mount Resque::Server, at: 'resque'
    end
  end

  match '/auth/:provider/callback' => 'authentications#create'   
  match 'dev' => 'dev#index', :via => [:get]
end

app/models/user.rb
# coding: utf-8

class User < ActiveRecord::Base                                                         
  has_one :user_setting
  accepts_nested_attributes_for :user_setting
  has_many :authentications  
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable
  before_save :ensure_authentication_token                

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_protected :id, :encrypted_password,:reset_password_token, :reset_password_sent_at, :remember_created_at, :sign_in_count, :current_sign_in_at, :last_sign_in_at, :current_sign_in_ip, :last_sign_in_ip, :password_salt, :authentication_token, :created_at, :updated_at     
  
  validates_format_of :email, :with =>  /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "은 형식이 올바르지 않습니다."  

  def admin?
    (self.id == 1) ? true : false
  end    
  
  def readable_object(version, current_user, includes = [])
    ret = {}

    case version.to_i
    when 1
       ret = {
         id: id,
         email: email,
         authentication_token: authentication_token,
         nickname: nickname,
         created_at: created_at.to_s(:normal_datetime),
         updated_at: updated_at.to_s(:normal_datetime)
       }
       if includes.include?(:user_setting)
         ret[:user_setting] = nil
         if user_setting
           ret[:user_setting] = user_setting.readable_object(version, current_user) 
         end
       end
    end

    ret
  end       
   
  
  def get_sns_client(provider)
    SnsClient::Base.new(self, provider)
  end
end

app/controllers/admin/users_controller.rb
# encoding: utf-8

class Admin::UsersController < Admin::AdminController
  # GET /users
  # GET /users.json
  def index
    @search = User.metasearch(params[:search])
    @users = @search.order('id DESC').page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
   def create
     respond_to do |format|
       format.html { super }
       format.json { 
         build_resource
         if resource.save
           render_resource_json resource, :include => [:user_setting], :message => 'Successfully signed up.'
         else
           render_fail_json(resource.errors.messages)
         end
       } 
     end
   end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  def create
    respond_to do |format|
      format.html { super }
      format.json { 
        warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#fail")
          
        # device로 로그인 시 app_delete_at를 초기화 해준다. 
        if (!params[:device].blank?) and (params[:device].in? %w( ios android ))
          user = User.find_by_email(params[:user][:email])
          user.user_setting.update_attributes app_deleted_at: nil
        end
        
        render_success_json('Successfully signed in.')
      } 
    end
  end 

  # response by json format when login fail.
  def fail    
    render_fail_json(flash[:alert])
  end
  
  def destroy
    respond_to do |format|
      format.html { super }
      format.json {
        sign_out(current_user)  
        render_success_json('Successfully signed out.')
      }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource 

  def show       
    @user = User.find(params[:id])
    
    respond_to do |format|
      format.html
      format.json { render_resource_json @user }
    end
  end      
  
  
  def edit
    @user = User.find(params[:id])
  end

  def update     
    @user = User.find(params[:id])
    
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to root_path, :notice => 'Successfully updated.' }
        format.json { render_resource_json @user, :message => 'Successfully updated.' }
      else                                                                 
        format.html { render action: 'edit' }    
        format.json { render_fail_json @user.errors.messages }
      end

    end
  end 

  def password
    @user = User.find(params[:id])
     
    respond_to do |format|
      if request.get? 
        format.html

      elsif request.put?  
        if @user.update_with_password(params[:user])
          format.html { redirect_to root_path, :notice => 'Successfully updated.' }
          format.json { render_resource_json @user, :message => 'Successfully updated.' }
        else         
          format.html { render action: 'password' }
          format.json { render_fail_json @user.errors.messages }                                                       
        end  
      end

    end
  end    
  
  def email_check
    user = User.find_by_email(params[:email])
                
    respond_to do |format|
      if user.nil?
        format.js { render text: 'true' }
        format.json { render json: { status_code: 'success', message: 'Email is unique.' }.to_json }
      else
        format.js { render text: 'false' }
        format.json { render json: { status_code: 'fail', message: 'Email is NOT unique.' }.to_json }
      end
    end
  end
  
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/_form.html.erb
  <div class="group">
    <%= f.label :email, t("activerecord.attributes.user.email", :default => "Email"), :class => :label %>
    <%= f.text_field :email, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :encrypted_password, t("activerecord.attributes.user.encrypted_password", :default => "Encrypted password"), :class => :label %>
    <%= f.text_field :encrypted_password, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :reset_password_token, t("activerecord.attributes.user.reset_password_token", :default => "Reset password token"), :class => :label %>
    <%= f.text_field :reset_password_token, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :reset_password_sent_at, t("activerecord.attributes.user.reset_password_sent_at", :default => "Reset password sent at"), :class => :label %>
    <%= f.datetime_select :reset_password_sent_at, :class => 'datetime_select' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :remember_created_at, t("activerecord.attributes.user.remember_created_at", :default => "Remember created at"), :class => :label %>
    <%= f.datetime_select :remember_created_at, :class => 'datetime_select' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :sign_in_count, t("activerecord.attributes.user.sign_in_count", :default => "Sign in count"), :class => :label %>
    <%= f.number_field :sign_in_count, :class => 'number_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :current_sign_in_at, t("activerecord.attributes.user.current_sign_in_at", :default => "Current sign in at"), :class => :label %>
    <%= f.datetime_select :current_sign_in_at, :class => 'datetime_select' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :last_sign_in_at, t("activerecord.attributes.user.last_sign_in_at", :default => "Last sign in at"), :class => :label %>
    <%= f.datetime_select :last_sign_in_at, :class => 'datetime_select' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :current_sign_in_ip, t("activerecord.attributes.user.current_sign_in_ip", :default => "Current sign in ip"), :class => :label %>
    <%= f.text_field :current_sign_in_ip, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :last_sign_in_ip, t("activerecord.attributes.user.last_sign_in_ip", :default => "Last sign in ip"), :class => :label %>
    <%= f.text_field :last_sign_in_ip, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :password_salt, t("activerecord.attributes.user.password_salt", :default => "Password salt"), :class => :label %>
    <%= f.text_field :password_salt, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :authentication_token, t("activerecord.attributes.user.authentication_token", :default => "Authentication token"), :class => :label %>
    <%= f.text_field :authentication_token, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :image_file_name, t("activerecord.attributes.user.image_file_name", :default => "Image file name"), :class => :label %>
    <%= f.text_field :image_file_name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :image_content_type, t("activerecord.attributes.user.image_content_type", :default => "Image content type"), :class => :label %>
    <%= f.text_field :image_content_type, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :nickname, t("activerecord.attributes.user.nickname", :default => "Nickname"), :class => :label %>
    <%= f.text_field :nickname, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :image_file_size, t("activerecord.attributes.user.image_file_size", :default => "Image file size"), :class => :label %>
    <%= f.number_field :image_file_size, :class => 'number_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :image_updated_at, t("activerecord.attributes.user.image_updated_at", :default => "Image updated at"), :class => :label %>
    <%= f.datetime_select :image_updated_at, :class => 'datetime_select' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :image_remote_url, t("activerecord.attributes.user.image_remote_url", :default => "Image remote url"), :class => :label %>
    <%= f.text_field :image_remote_url, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), admin_users_path, :class => "text_button_padding link_button" %>
</div>

app/views/admin/users/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/admin/users/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_user_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> User</h2>
    <div class="inner">
      <%= form_for @user, :url => admin_user_path(@user), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/users/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Users</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.admin_user.email", :default => t("activerecord.labels.email", :default => "Email")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @users.each do |user| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= user.id %>
          </td>
                    <td>
            <%= link_to user.email, admin_user_path(user) %>
          </td>
                    <td>
            <%= user.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_user_path(user) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_user_path(user) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_user_path(user), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/users/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  User</h2>
    <div class="inner">
      <%= form_for :user, :url => admin_users_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/users/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_user_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.admin_user.email", :default => t("activerecord.labels.email", :default => "Email")) %>:</b>
          <%= @user.email %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.encrypted_password", :default => t("activerecord.labels.encrypted_password", :default => "Encrypted password")) %>:</b>
          <%= @user.encrypted_password %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.reset_password_token", :default => t("activerecord.labels.reset_password_token", :default => "Reset password token")) %>:</b>
          <%= @user.reset_password_token %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.reset_password_sent_at", :default => t("activerecord.labels.reset_password_sent_at", :default => "Reset password sent at")) %>:</b>
          <%= @user.reset_password_sent_at %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.remember_created_at", :default => t("activerecord.labels.remember_created_at", :default => "Remember created at")) %>:</b>
          <%= @user.remember_created_at %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.sign_in_count", :default => t("activerecord.labels.sign_in_count", :default => "Sign in count")) %>:</b>
          <%= @user.sign_in_count %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.current_sign_in_at", :default => t("activerecord.labels.current_sign_in_at", :default => "Current sign in at")) %>:</b>
          <%= @user.current_sign_in_at %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.last_sign_in_at", :default => t("activerecord.labels.last_sign_in_at", :default => "Last sign in at")) %>:</b>
          <%= @user.last_sign_in_at %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.current_sign_in_ip", :default => t("activerecord.labels.current_sign_in_ip", :default => "Current sign in ip")) %>:</b>
          <%= @user.current_sign_in_ip %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.last_sign_in_ip", :default => t("activerecord.labels.last_sign_in_ip", :default => "Last sign in ip")) %>:</b>
          <%= @user.last_sign_in_ip %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.password_salt", :default => t("activerecord.labels.password_salt", :default => "Password salt")) %>:</b>
          <%= @user.password_salt %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.authentication_token", :default => t("activerecord.labels.authentication_token", :default => "Authentication token")) %>:</b>
          <%= @user.authentication_token %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.image_file_name", :default => t("activerecord.labels.image_file_name", :default => "Image file name")) %>:</b>
          <%= @user.image_file_name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.image_content_type", :default => t("activerecord.labels.image_content_type", :default => "Image content type")) %>:</b>
          <%= @user.image_content_type %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.nickname", :default => t("activerecord.labels.nickname", :default => "Nickname")) %>:</b>
          <%= @user.nickname %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.image_file_size", :default => t("activerecord.labels.image_file_size", :default => "Image file size")) %>:</b>
          <%= @user.image_file_size %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.image_updated_at", :default => t("activerecord.labels.image_updated_at", :default => "Image updated at")) %>:</b>
          <%= @user.image_updated_at %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.image_remote_url", :default => t("activerecord.labels.image_remote_url", :default => "Image remote url")) %>:</b>
          <%= @user.image_remote_url %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_user_path(@user), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_user_path(@user), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>